#!/usr/bin/env python3

import rospy
import actionlib
import random
from move_base_msgs.msg import MoveBaseFeedback, MoveBaseGoal, MoveBaseAction
from nav_msgs.msg import OccupancyGrid
from geometry_msgs.msg import Pose, Point, Quaternion

class Explore:
    '''
    Actions:        move_base - Turtlebot move_base
    Subscribers:    /move_base/global_costmap/costmap - OccupancyGrid of global costmap
    '''
    
    def __init__(self):
        '''
        Constructor of the Explore class
        initializes attributes, actions, and subscribers
        '''

        #initialize attributes
        self.map = OccupancyGrid()
        self.drate = rospy.Rate(1)
        self.status = 2    # 0:done 1:active 2:recursion depth reached

        #initialize action
        self.result = MoveBaseFeedback()
        self.move_base = actionlib.SimpleActionClient('move_base',MoveBaseAction)
        self.move_base.wait_for_server()

        #initialize subscribers
        rospy.Subscriber('/move_base/global_costmap/costmap',OccupancyGrid,self.map_callback)

        #allow time for subscriber initialization
        rospy.sleep(5)

        #start random exploration
        self.random_move()


    def map_callback(self,mdata):
        '''
        callback function for map subscriber
        updates map attribute
        '''
        self.map = mdata
    
    def move(self, goal):
        '''
        sends goal pose to the MoveBaseAction client
        updates status attribute
        args:
            goal (MoveBaseGoal): waypoint for Turtlebot
        '''
        # Send the goal pose to the MoveBaseAction server
        self.move_base.send_goal(goal,done_cb=self.done)
        self.status = 1

    #Action callback
    def done(self, gstatus, result):
        '''
        Action done callback function to update status and perform call a new random move
        args:
            gstatus (GoalStatus): integer representing goal status
            result: action result
        '''
        self.status = 0
        self.random_move()
    
    def random_move(self):
        '''
        Generates random goal withing global costmap
        if occupancy probability is less than 40 the goal is sent to move_base
        if occupancy probability is greater than 40 a new random goal is generated
        '''

        #Parse cost map information
        h = self.map.info.height
        w = self.map.info.width
        res = self.map.info.resolution
        x0 = self.map.info.origin.position.x
        y0 = self.map.info.origin.position.y

        #pick random cell in occupancy grid
        rand_h = random.randrange(0,h)
        rand_w = random.randrange(0,w)
        rand_cell = rand_h*w+rand_w

        #get occupancy probability
        prob = self.map.data[rand_cell]

        #set goal
        if prob < 40 and prob >= 0:
            #get x and y coordinate of cell
            xgoal = (rand_w*res)+x0
            ygoal = (rand_h*res)+y0
            print('xgoal: ' + str(xgoal))
            print('ygoal: ' + str(ygoal))
            print('')

            #send goal
            goal = MoveBaseGoal()
            goal.target_pose.header.frame_id = 'map'
            goal.target_pose.header.stamp = rospy.Time.now()
            mygoal = Pose(Point(xgoal,ygoal,0),Quaternion(0,0,0,1))
            goal.target_pose.pose = mygoal
            self.move(goal)
        
        #try again
        else:
            try:
                self.random_move()
            #avoid recursive error
            except:
                self.status = 2
                pass


def main():
    '''
    main function
    initializes node
    creates instance of Explore class
    '''
    
    rospy.init_node('explore')
    ex = Explore()

    while not rospy.is_shutdown():
        #avoid recursive eroor
        if ex.status == 2:
            ex.random_move()
    
    rospy.spin()

if __name__ == '__main__':
    try:
        main()
    except:
        rospy.ROSInterruptException