#!/usr/bin/env python3

import rospy
from nav_msgs.msg import OccupancyGrid
from geometry_msgs.msg import Twist

class Explore:
    '''
    '''
    
    def __init__(self):
        '''
        Constructor of the Explore class
        '''
        #initialize attributes
        self.map = OccupancyGrid()

        #initialize subscribers
        rospy.Subscriber('/map',OccupancyGrid,self.map_callback)

        #initialize publishers
        self.pub = rospy.Publisher('/cmd_vel',Twist,queue_size=10)


    def map_callback(self,mdata):
        '''
        callback function for map subscriber
        '''
        self.map = mdata


def main():
    '''
    '''
    rospy.init_node('explore')
    ex = Explore()

if __name__ = '__main__':
    try:
        main()
    except:
        rospy.ROSInterruptException